// <auto-generated />
using System;
using Homework1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Homework1.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250723023004_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Homework1.Models.MainText", b =>
                {
                    b.Property<string>("MainTextID")
                        .HasMaxLength(36)
                        .HasColumnType("char");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Photo")
                        .HasMaxLength(36)
                        .HasColumnType("char");

                    b.Property<string>("PhotoType")
                        .HasMaxLength(4)
                        .HasColumnType("char");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MainTextID");

                    b.ToTable("MainTexts");
                });

            modelBuilder.Entity("Homework1.Models.Reply", b =>
                {
                    b.Property<string>("ReplyID")
                        .HasMaxLength(36)
                        .HasColumnType("char");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainTextID")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ReplyID");

                    b.HasIndex("MainTextID");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("Homework1.Models.Reply", b =>
                {
                    b.HasOne("Homework1.Models.MainText", "MainText")
                        .WithMany("Replies")
                        .HasForeignKey("MainTextID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainText");
                });

            modelBuilder.Entity("Homework1.Models.MainText", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
